---
- name: Install Packages
  ansible.builtin.include_tasks: helper/install_packages.yml

- name: "Create '{{ basyx_server_user }}' User"
  ansible.builtin.user:
    name: "{{ basyx_server_user }}"

- name: Create folder for basyx components
  ansible.builtin.file:
    path: "{{ basyx_components_base_folder }}"
    state: directory

- name: Create folder for basyx server
  ansible.builtin.file:
    path: "{{ basyx_server_directory }}"
    state: directory
    owner: "{{ basyx_server_user }}"
    mode: '0755'

- name: Get service-facts of basyx_server
  ansible.builtin.service_facts:

- name: Install basyx_server as service
  when: ansible_facts.services[basyx_server_service_name+'.service'] is not defined
  block:
    - name: Git clone basyx_components repo
      ansible.builtin.git:
        repo: "{{ basyx_components_github_url }}"
        dest: "{{ basyx_components_base_folder }}"
      become: yes

    - name: Run mvn install
      ansible.builtin.shell: mvn install -Pdocker -DskipTests=true -DskipITs -Dmaven.javadoc.skip=true -Ddocker.skip=true -DdockerCompose.skip=true -f {{ basyx_components_base_folder }}/basyx.components/pom.xml

    - name: Copy files/folders from target folder
      ansible.builtin.copy:
        src: "{{ basyx_server_target_folder }}/{{ item.src }}"
        dest: "{{ basyx_server_directory }}"
        owner: "{{ basyx_server_user }}"
        mode: "{{ item.mode }}"
        remote_src: true
      loop:
        - src: "basyx.components.AASServer-{{ basyx_components_version }}.jar"
          mode: "0644"
        - src: lib
          mode: "0744"

    - name: "Copy config files"
      ansible.builtin.template:
        src: "{{ item.template_file }}"
        dest: "{{ basyx_server_directory }}/{{ item.config_file }}"
        owner: "{{ basyx_server_user }}"
        mode: '0644'
      loop: "{{ basyx_server_config_files }}"

    - name: "Copy service file"
      ansible.builtin.template:
        src: basyx_server.service.j2
        dest: "/etc/systemd/system/{{ basyx_server_service_name }}.service"
        force: yes

    - name: "Start basyx_server service"
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: "{{ basyx_server_service_name }}"


